# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md

root: true

env:
  browser: true
  es6: true
  jest: true
  node: true

overrides:
  # Linter settings for TypeScript
  - files: ["src/**/*.ts{,x}"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      project: tsconfig.json
      ecmaFeatures:
        jsx: true
    plugins:
      - "@typescript-eslint"
    extends:
      - react-app
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking

settings:
  react:
    version: "detect"
