# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
# https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md

root: true

env:
  es6: true
  node: true

overrides:
  # Linter settings for JavaScript
  - files: ["**/*.js"]
    parserOptions:
      ecmaVersion: 2020
    env:
      es6: true
    extends:
      - oclif
      - eslint:recommended
      - prettier
      - "plugin:chai-friendly/recommended"
    rules:
      no-unused-expressions: 0
      no-multi-assign: warn

  # Linter settings for TypeScript
  - files: ["**/*.ts"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      project: tsconfig.json
    plugins:
      - "@typescript-eslint"

    excludedFiles: ["**/fixtures/**/*.ts"]
    extends: 
      - oclif
      - oclif-typescript
      - eslint:recommended
      - prettier
      - prettier/@typescript-eslint
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    rules:
      no-console: 0
      valid-jsdoc: 0
      no-warning-comments: 0
      no-use-before-define: 0
      prefer-promise-reject-errors: 0
      no-await-in-loop: 0
      no-negated-condition: 0
      no-implicit-coercion: 0
      new-cap: 0
      no-dupe-else-if: 0
      no-import-assign: 0
      no-setter-return: 0
      camelcase: warn
      no-case-declarations: warn
      "@typescript-eslint/ban-types": 0
      "@typescript-eslint/no-use-before-define": 0
      "@typescript-eslint/unbound-method": warn
      "@typescript-eslint/ban-ts-comment": warn
      "@typescript-eslint/prefer-regexp-exec": warn
      "@typescript-eslint/no-non-null-assertion": warn
      "@typescript-eslint/no-unsafe-call": warn
      "@typescript-eslint/no-unsafe-return": warn
      "@typescript-eslint/no-unsafe-member-access": warn
      "@typescript-eslint/no-unsafe-assignment": warn
      "@typescript-eslint/restrict-plus-operands": warn
      "@typescript-eslint/restrict-template-expressions": warn
      "@typescript-eslint/no-unnecessary-type-assertion": warn
      "@typescript-eslint/await-thenable": warn
      "@typescript-eslint/require-await": warn
      "@typescript-eslint/no-var-requires": warn
