plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  redoc@*:
    dependencies:
      call-me-maybe: "*"
      yaml: "*"
      fast-safe-stringify: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
