export enum BillingCategories {
  Uncategorized = "uncategorized",
  Shipping = "shipping",
  Insurance = "insurance",
  Confirm = "confirm",
  Discount = "discount",
  FuelCharge = "fuel_charge",
  AdditionalFees = "additional_fees",
  Tariff = "tariff",
  Tax = "tax",
  Delivery = "delivery",
  Handling = "handling",
  SpecialGoods = "special_goods",
  Pickup = "pickup",
  LocationFee = "location_fee",
  Oversize = "oversize",
  Returns = "returns",
  Notifications = "notifications",
}
