apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  annotations:
    shipkube/version: "0.0.5"
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | default "" | quote }}
  {{- end}}
