{{ if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  annotations:
    shipkube/version: "0.0.5"
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | default "" | b64enc }}
  {{- end }}
{{ end }}
