apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  annotations:
    release/version: {{ printf "%s.%s" .Chart.Name .Chart.Version }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.service.port }}
