id: 03318192-3e6c-475f-a496-a4f17c1dbcae
identifiers:
  apiCode: PAK
name: Cargo Inc Package
description: Your own packaging, up to 100 kilograms
requiresWeight: true
requiresDimensions: true

localization:
  en-GB:
    name: Parcel

  en-US:
    description: Your own packaging, up to 120 pounds

  es:
    name: empaquetar
    description: Su propio embalaje, hasta 100 kilogramos

  zh:
    name: 收拾东西
    description: 您自己的包装，最多100公斤
