ingress:
  annotations:
    kubernetes.io/ingress.class: nginx-kube-seplocal
  hosts:
    - shipengine-connect-website-v1-prod.kube.seplocal.com

env:
  PGHOST: shipengine-connect-shared-prod.cluster-cby3ni8twmoi.us-east-1.rds.amazonaws.com
  ASPNETCORE_ENVIRONMENT: Production

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi
