ingress:
  annotations:
    kubernetes.io/ingress.class: nginx-kube-seplocal
  hosts:
    - shipengine-connect-website-v1-prod.kube.seplocal.com

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 1Gi
