name: cli

on:
  push:
    branches:
      - master
    paths:
      - "packages/cli/**"
      - ".github/workflows/cli.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "packages/cli/**"
      - ".github/workflows/cli.yaml"

jobs:
  test:
    name: ${{ matrix.dir }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node@14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn lint
        working-directory: packages/cli
        run: yarn lint

      - name: yarn build
        working-directory: packages/cli
        run: yarn build

      - name: yarn test
        working-directory: packages/cli
        run: yarn test
        env:
          HOME: ./

  publish:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    defaults:
      run:
        working-directory: packages/cli

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: packages/cli
        run: yarn build

      - name: Publish to NPM
        working-directory: packages/cli
        run: yarn publish --non-interactive --no-git-tag-version
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
