name: V1 GitHub Pages

on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: install node@14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install dependencies
        run: yarn install --immutable --immutable-cache

      - name: test
        run: yarn run lint

      - name: build
        run: yarn run build

      - name: next.js export
        run: yarn run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/v1' }}
        with:
          cname: connect-v1.shipengine.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-v1
          publish_dir: ./out
