name: shipping-runtime publish

on:
  push:
    branches:
      - master
    paths:
      - "packages/shipping-runtime/**"

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: packages/shipping-runtime

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: packages/shipping-runtime
        run: yarn build

      - name: Increment version
        working-directory: packages/shipping-runtime
        run: |
          # Configure git for commits
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Increment package version
          yarn run release

      - name: Publish to NPM
        working-directory: packages/shipping-runtime
        run: yarn publish --non-interactive --no-git-tag-version
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
